### ISSUE TITLE
Stream overwhelmed by `ResponseStream` causing memory leak

### ISSUE THREAD

**Issue by zckevin** [flatiron/union#54]
https://github.com/flatiron/union/blob/master/lib/response-stream.js#L162

```javascript
ResponseStream.prototype.write = function (data) {
  this.modified = true;

  if (this.writable) {
    this.emit('data', data);
  }
};
```

This function push data into destination streams, eg. HTTP response, without considering back pressure, it will blow the memory up when serving large static files.

Related issue: https://github.com/indexzero/http-server/issues/138

**Comment by roccomuso** [comment]
+1

**Comment by jcrugzz** [comment]
This module shouldn't be used anymore but will see if your patch fixes and still passes tests
